.TH GENERATE-PASSWORD 1 "June 2023" "generate-password 1.x" "User Commands"
.SH NAME
generate-password \- Generate a password
.SH SYNOPSIS
.B generate-password
\fI\-\-list-digests\fR | [\fI\-\-length <minimum>\fR]
[\fI\-\-maximum\-length <maximum>\fR] [\fI\-\-digest <name>\fR]
.SH DESCRIPTION
This tool can be used to generate a password from your command line. The
tool currently supports two commands. The default is to generate a password.
In that case you can specific the minimum length with \-\-length and
the maximum length with \-\-max\-length. You can also change the default
digest with the \-\-digest option.
.PP
The other command is the \-\-list\-digests which allows you to see the
list of available digests types. All of these names can be used with the
\-\-digest command line option when generating a password.
.SH AUTHOR
Written by Alexis Wilke <alexis@m2osw.com>.
.SH "REPORTING BUGS"
Report bugs to <https://github.com/m2osw/safepasswords/issues>.
.br
iplock home page: <https://snapwebsites.org/project/safepasswords>.
.SH COPYRIGHT
Copyright \(co 2011-2023 Made to Order Software Corporation
.br
License: GPLv3
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
